name: Deploy on org

on:
  push:
    branches:
      - develop
      - ci-cd-poc

jobs:
  deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Authenticate using SFDX_AUTH_URL"
        run: |
          echo ${{ secrets.SFDX_AUTH_URL_POC }} | sf org login sfdx-url -s -u

      - name: "Validate"
        run: |
          cd "IVF Portal App" && sf project deploy validate -d ./force-app/ -l RunSpecifiedTests --tests "ChangePasswordControllerTest" -w 30

      - name: "Deploy"
        run: |
          cd "IVF Portal App" && sf project deploy start -d ./force-app/ -l RunSpecifiedTests --tests "ChangePasswordControllerTest" -w 30
